name: Generate PBF Glyphs Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install build-glyphs
        run: npm install -g build-glyphs

      - name: Convert TTF to PBF
        run: |
          mkdir -p out_glyphs/Vazirmatn-Black
          build-glyphs Vazirmatn-Black.ttf out_glyphs/Vazirmatn-Black

      - name: Upload Glyphs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-map-glyphs
          path: out_glyphs/
          retention-days: 7
